global:
  scrape_interval:     10s
  external_labels:
    monitor: legumes

scrape_configs:
  - job_name: legumes
    scrape_interval: 10s
    static_configs:
      - targets: [legumes:8080]


  - job_name: loki
    scrape_interval: 10s
    static_configs:
      - targets: [loki:3100]

  - job_name: tempo
    scrape_interval: 10s
    static_configs:
      - targets: [tempo:3200]