apiVersion: v1
data:
  config.yaml: |-
    enableUserWorkload: true
    prometheusK8s:
      retention: 24h
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
