apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: otel-collector
  name: otel-collector
  namespace: quarkus-demo
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  - interval: 30s
    port: prometheus-exporter
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector