global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'vegetables:8080'
          - 'superheroes:8080'
    consul_sd_configs:
    - server: 'host.docker.internal:8500'
