receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: otel-collector:55680
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: 'otelcol'
#          scrape_interval: 10s
#          static_configs:
#            - targets: [ '0.0.0.0:8888' ]
#          metric_relabel_configs:
#            - source_labels: [ __name__ ]
#              regex: '.*grpc_io.*'
#              action: drop

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp,otlp/2]
      processors: []
#      exporters: [jaeger]
      exporters: [logging]
    metrics:
      receivers: [otlp,otlp/2]
      processors: []
      exporters: [logging]