receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: otel-collector:55680

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp,otlp/2]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [ otlp,otlp/2 ]
      processors: [ ]
      exporters: [ logging ]