receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ ]
      #      exporters: [jaeger]
      exporters: [ logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ logging ]