version: "3"
services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changeit
      POSTGRES_USER: pguser
      POSTGRES_DB: test
    ports:
      - '5432:5432'

  grafana:
    image: grafana/otel-lgtm:latest
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'