apiVersion: 1

datasources:
- name: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  jsonData:
    derivedFields:
      - datasourceUid: jaeger_uid
        matcherRegex: "\"trace_id\": \\\"(.+?)\\\""
        name: TraceID
        url: "$${__value.raw}"
- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger_uid #Matches loki.derviedFields.datasourceUid
  url: http://jaeger-query:16686
  editable: true
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
