version: "2"
services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changeit
      POSTGRES_USER: pguser
      POSTGRES_DB: test
    ports:
      - '5432:5432'
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268" # receive OpenTracing traces
      - "14250:14250" # receive from otel-collector
  # Collector. Currently, included with jaeger-all-in-one.
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
      - "8888:8888" # Otel Colletor Metric
      - "8889:8889" # Prometheus Exporter
    depends_on:
      - jaeger-all-in-one
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector
